// 按需全局引入 vant组件
import Vue from 'vue'
import { Button, List, Cell, Tabbar, TabbarItem, Image as VanImage, Icon, Form, Field, NavBar, Sticky, Checkbox, CheckboxGroup, Picker, ActionSheet, Search, Tag, Tab, Tabs, Swipe, SwipeItem, Lazyload, Rate } from 'vant'
Vue.use(Button)
Vue.use(Cell)
Vue.use(List)
Vue.use(Tabbar).use(TabbarItem)
Vue.use(Icon)
Vue.use(VanImage)
Vue.use(Form)
Vue.use(Field)
Vue.use(NavBar)
Vue.use(Sticky)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Picker)
Vue.use(ActionSheet)
Vue.use(Search)
Vue.use(Tag)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Lazyload)
Vue.use(Rate)
